project:
  type: website
  output-dir: docs

website:
  title: "Sarena Manee Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: INat.qmd
        text: Lesson Plan
        
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: source

